modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="tobillomod_2"
version="1.0.0"
displayName="Tobillomod II"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Sanicoh"
description="A mod where randomness mixes with normal content."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tobillomod_2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration